name: Hello, World!
description: Greet someone and record the time
author: GitHub Actions

# Define your inputs here.
inputs:
  repo-token:
    description:
      'Token for the repository. Can be passed in using {{ secrets.GITHUB_TOKEN
      }}'
    required: true

# Define your outputs here.
outputs:

runs:
  using: node20
  main: dist/index.js
