name: Example Workflow

on:
  pull_request:
    types: [opened, reopened]

jobs:
  demo:
    name: Testing stuff
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Test action
        id: test-action
        uses: ./
          with:
            repo-token: ${{ secrets.GITHUB_TOKEN  }}
