name: Example Workflow

on:
  pull_request:
    types: [opened]

jobs:
  demo:
    name: Testing stuff
    runs-on: ubuntu-latest

    steps:
      - name: Print to Log
        id: print-to-log
        uses: ClaireSimmonds/hello-world-javascript-action@main
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN  }}
