name: Example Workflow

on:
  pull_request:
    types: [opened, reopened]


jobs:
  demo:
    name: Testing stuff
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test action
        uses: ./
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN  }}
