name: Example Workflow

on:
  pull_request:


jobs:
  dump:
    name: Dump context
    runs-on: ubuntu-latest

    steps:
      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v2
  demo:
    name: Testing stuff
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test action
        uses: ./
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN  }}
