name: Metrics Testing

on:
  pull_request:
    types: [opened, reopened]

jobs:
  extract:
    name: Extract PR event details
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Extract data
        uses: ./
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN  }}
