name: Say Something

on:
  workflow_call:
    inputs:
      greeting:
        type: string
        required: true

permissions:
  contents: read

jobs:
  print-stuff:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo Say ${{ inputs.greeting }}
